# Generated by Django 5.1.3 on 2025-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
